version: "3.8"

services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: "./back"
    ports:
      - "5000:5000"

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./front
    ports:
      - "3000:3000"
